# Generated by Django 5.0.1 on 2024-01-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='link',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        )
    ]
