# Generated by Django 5.0.1 on 2024-01-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_poem_link_alter_poem_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='link',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
