# Generated by Django 5.0.1 on 2024-01-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_poem_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='body',
            field=models.TextField(),
        ),
    ]
