# Generated by Django 4.1 on 2024-01-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_alter_poem_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
